// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/announcements/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/announcements/create.post').default>>>>
    }
    '/api/announcements/fetchAll': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/announcements/fetchAll.get').default>>>>
    }
    '/api/messages/send-announcement': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/send-announcement.post').default>>>>
    }
    '/api/messages/send-newsletter': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/send-newsletter.post').default>>>>
    }
    '/api/newsletters/create': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/newsletters/create').default>>>>
    }
    '/api/newsletters/fetchAll': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/newsletters/fetchAll').default>>>>
    }
    '/api/notifications/check-fcm': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/check-fcm').default>>>>
    }
    '/api/notifications/fetchUnsubscribers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/fetchUnsubscribers.get').default>>>>
    }
    '/api/notifications/print-letters': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/print-letters').default>>>>
    }
    '/api/notifications/register-token': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/register-token').default>>>>
    }
    '/api/notifications/send-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/send-otp.post').default>>>>
    }
    '/api/notifications/send': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/send').default>>>>
    }
    '/api/notifications/token': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/token').default>>>>
    }
    '/api/notifications/update-subscription': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/update-subscription').default>>>>
    }
    '/api/notifications/verify-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/verify-otp.post').default>>>>
    }
    '/api/schools/fetchById': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schools/fetchById').default>>>>
    }
    '/api/schools/fetchByUserId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schools/fetchByUserId').default>>>>
    }
    '/api/schools/fetchGradesClassesStaff': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schools/fetchGradesClassesStaff.get').default>>>>
    }
    '/api/schools/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schools/login.post').default>>>>
    }
    '/api/schools/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schools/register.post').default>>>>
    }
    '/api/stakeholders/assignGroup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stakeholders/assignGroup.post').default>>>>
    }
    '/api/stakeholders/fetchByRole': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stakeholders/fetchByRole.get').default>>>>
    }
    '/api/stakeholders/getTotalByGroup': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stakeholders/getTotalByGroup.get').default>>>>
    }
    '/api/stakeholders/update-stakeholder': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stakeholders/update-stakeholder').default>>>>
    }
    '/api/stakeholders/upload-parent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stakeholders/upload-parent.post').default>>>>
    }
    '/api/stakeholders/upload-staff': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stakeholders/upload-staff.post').default>>>>
    }
    '/api/stakeholders/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stakeholders/verify.post').default>>>>
    }
    '/api/storyblok/webhook': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/storyblok/webhook').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}